name: Front Update

on:
  push:
    paths:
      - "calculator/*"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_CLOUDFRONT_DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Listing files
        working-directory: ./calculator
        run: ls -lah

      - name: Use Node.js 15
        uses: actions/setup-node@v3
        with:
          node-version: 15
      
      - name: Installing dependencies
        working-directory: ./calculator
        run:  npm install

      - name: Running Build
        working-directory: ./calculator
        run: npm run build --if-present

      - name: Running Tests
        working-directory: ./calculator
        run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: node
          path: ${{ github.workspace }}/calculator/build
      
  Front_refresh:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Create build folder
        run: mkdir build
      
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: node
          path: build

      - name: Listing files
        run: ls -lah ./build

      - name: "Deploy to AWS S3"
        run: aws s3 sync ./build/ s3://${{ AWS_S3_BUCKET_NAME }} --delete --cache-control max-age=604800

      - name: "Create AWS Cloudfront Invalidation"
        run: aws cloudfront create-invalidation --distribution-id ${{ AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"


