name: Front Update

on:
  push:
    paths:
      - "calculator/*"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12, 14, 15 ]


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Listing files
        working-directory: ./calculator
        run: ls -lah

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        working-directory: ./calculator
        run:  npm install

      - name: Running Build
        working-directory: ./calculator
        run: npm run build --if-present

      - name: Running Tests
        working-directory: ./calculator
        run: npm test

      - name: Listing files
        working-directory: ./calculator
        run: ls -lah