name: Front Update

on:
  push:
    paths:
      - "calculator/*"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x,12.x,14.x,15.x]


    steps:
      - uses: action/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version ${{ matrix.node-version }}
        run: cd ${{ github.workspace }}/calculator
        run: npm install
        run: npm run build --if-present
        run: npm test

      - name: Listing files
        run: ls -lah